export enum OperationApiResponseCodes {
  CountryIsRestricted = -11,
  TooManyAttempts = -10,
  Expired = -9,
  SystemError,
  FileNotFound = -6,
  FileWrongExtension,
  OldPasswordNotMatch,
  UserNotExist,
  UserExists,
  InvalidUserNameOrPassword,
  Ok,
  DayOff,
  MinOperationLotViolated,
  MaxOperationLotViolated,
  MaxPositionByInstrumentViolated,
  InsufficientMargin,
  NoLiquidity,
  PositionNotFound,
  TpIsTooClose,
  SlIsTooClose,
  PendingOrderNotFound,
  AccountNotFound,
  InstrumentNotFound,
  InstrumentCanNotBeUsed,
  OperationIsNotPossibleDuringSwap,
  MaxAmountPendingOrders,
  TechnicalError,
  MultiplierNotFound,
  MaximumAmountOfDemoAccount,
  TradingDisabled,
  MaxOpenPositionsAmount,
}
