const Fields = {
  ACCOUNT_ID: 'accountId',
  EMAIL: 'email',
  OLD_PASSWORD: 'oldPassword',
  PASSWORD: 'password',
  USER_AGREEMENT: 'userAgreement',
  REPEAT_PASSWORD: 'repeatPassword',
  TAKE_PROFIT: 'tp',
  TAKE_PROFIT_TYPE: 'tpType',
  STOP_LOSS: 'sl',
  STOP_LOSS_TYPE: 'slType',
  AMOUNT: 'investmentAmount',
  INSTRUMNENT_ID: 'instrumentId',
  MULTIPLIER: 'multiplier',
  PURCHASE_AT: 'openPrice',
  OPERATION: 'operation',
  COUNTRY_OF_CITIENZENSHIP: 'countryOfCitizenship',
  COUNTRY_OF_RESIDENCE: 'countryOfResidence',
  CITY: 'city',
  DATE_OF_BIRTH: 'dateOfBirth',
  FIRST_NAME: 'firstName',
  LAST_NAME: 'lastName',
  PHONE: 'phone',
  POSTAL_CODE: 'postalCode',
  SEX: 'sex',
  US_CITIZEN: 'uSCitizen',
  ADDRESS: 'address',
  CUSTOM_COUNTRY: 'customCountryCode',
  CUSTON_PASSPORT_ID: 'customPassportId',
  CUSTOM_PROOF_OF_ADDRESS: 'customProofOfAddress',
};

Object.freeze(Fields);
export default Fields;
