const mixpanelEvents = {
  LAST_LOGIN: 'last login',
  LOGIN_VIEW: 'login view',
  LOGIN: 'login',
  LOGIN_FAILED: 'login failed',
  SIGN_UP_VIEW: 'sign up view',
  SIGN_UP: 'sign up',
  SIGN_UP_FAILED: 'sign up failed',
  FIRST_NAME: '$first_name',
  LAST_NAME: '$last_name',
  EMAIL: '$email',
  PHONE: '$phone',
  AVATAR: '$avatar',
  USER_KYC_STATUS: 'user kyc status',
  BRAND_NAME: 'brand name',
  ACCOUNT_CURRENCY: 'account_currency',
  ACCOUNT_TYPE: 'account_type',
  ACCOUNTS_ALL: 'accounts_all',
  REG_DATE: 'reg_date',
  TOTAL_ACCOUNT_PNL: 'total_account_p&l',
  TOTAL_ACCOUNT_DEPOSITS_NUMBER: 'total_account_deposits_number',
  TOTAL_ACCOUNT_WITHDRAW_NUMBER: 'total_account_withdraw_number',
  TOTAL_ACCOUNT_TRADES_NUMBER: 'total_account_trades_number',
  MARKET_ORDER: 'market order',
  MARKET_ORDER_FAILED: 'market order failed',
  LIMIT_ORDER: 'limit order',
  LIMIT_ORDER_FAILED: 'limit order failed',
  FORGOT_PASSWORD: 'forgot password',
  FORGOT_PASSWORD_VIEW: 'forgot password view',
  FORGOT_PASSWORD_SUBMIT: 'forgot password submit',
  FORGOT_PASSWORD_SET_NEW: 'forgot password set new',
  DEPOSIT: 'deposit',
  DEPOSIT_LIST_VIEW: 'deposit list view',
  DEPOSIT_METHOD_VIEW: 'deposit method view',
  DEPOSIT_FAILED: 'deposit failed',
  CLOSE_ORDER: 'close order',
  CLOSE_ORDER_FAILED: 'close order failed',
  WITHDRAW_VIEW: 'withdraw view',
  WITHDRAW_HISTORY_VIEW: 'withdraw history view',
  KYC_STEP_1: 'kyc step 1',
  KYC_STEP_2: 'kyc step 2',
  KYC_STEP_3: 'kyc step 3',
};

Object.freeze(mixpanelEvents);

export default mixpanelEvents;
