const mixapanelProps = {
  EMAIL: '$email',
  EMAIL_FAILED: 'Email',
  FIRST_NAME: '$first_name',
  LAST_NAME: '$last_name',
  PHONE: '$phone',
  BRAND_NAME: 'Brand Name',
  ACCOUNTS: 'Accounts',
  FUNDED_TRADER: 'Funded trader',
  TRADER_ID: 'Trader ID',
  PLATFORMS_USED: 'Platforms Used',
  KYC_STATUS: 'KYC Status',
  DEPOSIT_METHOD: 'Deposit Method',
  AMOUNT: 'Amount',
  ACCOUNT_ID: 'Account id',
  ACCOUNT_CURRENCY: 'Account currency',
  INSTRUMENT_ID: 'Instrument ID',
  MULTIPLIER: 'Multiplier',
  TREND: 'Trend',
  SLTP: 'SLTP',
  SL_TYPE: 'SL type',
  TP_TYPE: 'TP type',
  SL_VALUE: 'SL value',
  TP_VALUE: 'TP value',
  AVAILABLE_BALANCE: 'Available Balance',
  ACCOUNT_TYPE: 'Account Type',
  EVENT_REF: 'Event ref',
  ERROR_TEXT: 'Error text',
  SERVER_ERROR: 'Server error',
  POSITION_ID: 'Position ID',
  WITHDRAWAL_METHOD: 'Withdraw method',
};

Object.freeze(mixapanelProps);

export default mixapanelProps;
